name: Close Issue Message
on:
  issues:
    types: [closed]

jobs:
  close-issue:
    runs-on: ubuntu-latest
    permissions:
        issues: write
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: aws-actions/closed-issue-message@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            This issue is now closed. Comments on closed issues are hard for our team to see. 
            If you need more assistance, please open a new issue that references this one.
